### ISSUE TITLE
Output is always in XML format, regardless of MOCHA_REPORTER variable

### ISSUE THREAD

**Issue by grahaml** [apipkin/reporter-file#1]
Not sure if there's something wrong with my setup, or something wrong with the plugin, but I am not getting the results I expect.

I am trying to use `reporter-file` in a Gulp task using `gulp-mocha`. Before calling `mocha()` I set the appropriate environment variables for `reporter-file`. Like so (coffeescript source):

``` coffeescript

# Runs mocha tests, using `reporter-file` as the reporter
gulp.task 'mocha', ['set-env-vars'], (done) ->

  # Require reporter-file here, now that the env vars have been added by the `set-env-vars` task
  reporterFile = require 'reporter-file'

  gulp.src(['test/spec_init.coffee','test/**/*_spec.coffee'], {read: no})
  .pipe(mocha(
    compilers: 'coffee:coffee-script/register'
    reporter: reporterFile
    verbose: false
  ))

# Sets the proper environment variables for `reporter-file`
gulp.task 'set-env-vars', (done) ->
  env(
    vars:
      # Env vars needed for repoter-file to properly direct traffic
      MOCHA_REPORTER: 'HTMLCov'
      MOCHA_REPORTER_FILE: 'coverage/coverage.html'
  )

  done()
```

Now I know that setting the vars is working, because node throws an error if I use a bad reporter name, eg. if I use...

``` coffeescript
...
# EXAMPLE OF BAD REPORTER NAME
env(
  vars:
    MOCHA_REPORTER: 'html-cov'
    ...
)
```

then I get (note: most of stack trace removed for brevity)...

```
[17:45:41] 'mocha' errored after 35 ms
[17:45:41] TypeError: Cannot read property 'prototype' of undefined
 at Object.<anonymous> (/Users/graham.losee/Projects/learning/messing-with-mocha/node_modules/reporter-file/lib/reporter-file.js:78:34)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
...
```

Now, if I use the correctly spelled `HTMLCov` as the `MOCHA_REPORTER` then I see the expected HTML output in my console window, but `coverage.html` has an XML file structure instead, like this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Mocha Tests" tests="16" failures="0" errors="0" skipped="0" timestamp="Tue, 28 Oct 2014 21:48:59 GMT" time="0.031">
    <testcase classname="THE (js)DOM" name="has a `window` object" time="0.001"/>
    <testcase classname="THE (js)DOM" name="has a `document` object" time="0"/>
    <testcase classname="THE (js)DOM" name="can create elements and add them to the DOM" time="0.001"/>
    <testcase classname="THE (js)DOM jQuery" name="has access to jQuery as `$`" time="0"/>
    <testcase classname="THE (js)DOM jQuery" name="has access to jQuery as `jQuery`" time="0"/>
    <testcase classname="Task instance" name="should have a name" time="0"/>
    <testcase classname="Task instance" name="should be initially incomplete" time="0"/>
    <testcase classname="Task instance" name="should be able to be completed" time="0"/>
    <testcase classname="Task instance" name="should be able to be dependent on another task" time="0"/>
    <testcase classname="Task instance" name="should refuse completion if it is dependent on an uncompleted task" time="0.001"/>
    <testcase classname="TaskList instance" name="should start with no tasks" time="0"/>
    <testcase classname="TaskList instance" name="should accept new tasks as tasks" time="0"/>
    <testcase classname="TaskList instance" name="should accept new tasks as strings" time="0"/>
    <testcase classname="TaskList instance" name="should allow you to remove tasks by passing a task to remove" time="0"/>
    <testcase classname="TaskList instance" name="should print out your list of tasks" time="0.001"/>
    <testcase classname="TaskList instance" name="should add a list of tasks to the DOM" time="0.022"/>
</testsuite>
```

I was under the impression that this plugin would output the report to the file I specify. Is there anything wrong with my setup?

Thanks in advance!

**Comment by apipkin** [comment]
So the idea is to use one reporter to report to the screen and then use `reporter-file` to save the previously ran report to the file? That's something I can get behind for sure.

**Comment by grahaml** [comment]
Well not exactly - what I'm personally trying to do is just make the report type that I want be written out to `MOCHA_REPORTER_FILE` instead of the console. Right now the type that I specify as `MOCHA_REPORTER` gets output into the console, and the `xunit` xml report gets output to the file specified as `MOCHA_REPORTER_FILE`. The reverse is what I need - an HTMLCov report output to the file and not to the console.
